const {test}=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');
const {active,identity,entitlement}=require('../workspace');const {signatureValid,nextMonth,paidOrder}=require('../billing');
test('Pro access requires active, unexpired paid period',()=>{const now=Date.parse('2026-09-09T10:00:00Z');assert.equal(active({plan:'pro',status:'active',paid_until:'2026-10-09'},now),true);for(const e of [{plan:'once',status:'active',paid_until:'2026-10-09'},{plan:'pro',status:'past_due',paid_until:'2026-10-09'},{plan:'pro',status:'active',paid_until:'2026-09-09T10:00:00Z'},{plan:'pro',status:'active',paid_until:'invalid'}])assert.equal(active(e,now),false);});
test('Shopify signature verification rejects altered or missing signatures',()=>{const body=Buffer.from('{"id":1}'),key='test-key';const signature=crypto.createHmac('sha256',key).update(body).digest('base64');assert.equal(signatureValid(body,signature,key),true);assert.equal(signatureValid(Buffer.from('{"id":2}'),signature,key),false);assert.equal(signatureValid(body,'bad',key),false);assert.equal(signatureValid(body,signature,''),false);});
test('Calendar-month periods clamp the final day',()=>{assert.equal(nextMonth('2026-01-31T12:34:56Z'),'2026-02-28T12:34:56.000Z');assert.equal(nextMonth('2028-01-31T12:34:56Z'),'2028-02-29T12:34:56.000Z');});
test('Only a real paid R299 ZAR Pro variant can create a period',()=>{const o={id:42,test:false,financial_status:'paid',currency:'ZAR',email:'Buyer@example.com',processed_at:'2026-09-01T10:00:00Z',line_items:[{variant_id:99,price:'299.00',quantity:1,total_discount:'0.00'}]};assert.equal(paidOrder(o,'99').paid_until,'2026-10-01T10:00:00.000Z');for(const patch of [{test:true},{currency:'USD'},{financial_status:'pending'},{line_items:[{variant_id:88,price:'149.00',quantity:1}]},{email:''},{processed_at:'invalid'}])assert.equal(paidOrder({...o,...patch},'99'),null);assert.equal(paidOrder(o,''),null);});
function response(){return {statusCode:200,headers:{},set(k,v){this.headers[k]=v;return this;},status(n){this.statusCode=n;return this;},json(d){this.data=d;return this;}};}
test('Identity denies requests when account services are absent',async()=>{const res=response();let called=false;await identity({headers:{}},res,()=>called=true);assert.equal(res.statusCode,503);assert.equal(called,false);});
test('Verified account identity still requires AAL2',async()=>{const saved={...process.env};const original=global.fetch;process.env.SUPABASE_URL='https://example.test';process.env.SUPABASE_ANON_KEY='public-test';process.env.SUPABASE_SERVICE_ROLE_KEY='server-test';global.fetch=async()=>({ok:true,json:async()=>({id:'test-id',email_confirmed_at:'2026-01-01'})});try{const token='header.'+Buffer.from(JSON.stringify({sub:'test-id',aal:'aal1',exp:Date.now()/1000+60})).toString('base64url')+'.signature';const res=response();let called=false;await identity({headers:{authorization:'Bearer '+token}},res,()=>called=true);assert.equal(res.statusCode,403);assert.equal(res.data.code,'MFA_REQUIRED');assert.equal(called,false);}finally{global.fetch=original;for(const k of ['SUPABASE_URL','SUPABASE_ANON_KEY','SUPABASE_SERVICE_ROLE_KEY']){if(saved[k]===undefined)delete process.env[k];else process.env[k]=saved[k];}}});
test('No paid orders means no dashboard access',async()=>{const original=global.fetch;global.fetch=async()=>Response.json([]);try{const res=response();let called=false;await entitlement({account:{id:'test-id'}},res,()=>called=true);assert.equal(res.statusCode,402);assert.equal(called,false);}finally{global.fetch=original;}});
