const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {parseHTML}=require('linkedom');
function setup(data){
 const {document}=parseHTML(fs.readFileSync(path.join(__dirname,'../../services/index.html'),'utf8'));
 const form=document.getElementById('brief-form'),status=document.getElementById('brief-status');let clicks=[],blob;
 for(const el of form.querySelectorAll('input,textarea,select')){el.value=data[el.name]||'';el.setCustomValidity=function(s){this.error=s;};}
 form.reportValidity=()=>[...form.querySelectorAll('[required]')].every(el=>el.value.trim()&&!el.error);
 const create=document.createElement.bind(document);document.createElement=tag=>{const el=create(tag);if(tag==='a')Object.defineProperty(el,'href',{value:'',writable:true});if(tag==='a')el.click=()=>clicks.push({href:el.href,download:el.download,target:el.target,rel:el.rel});return el;};
 const context={document,FormData:class{constructor(){return Object.entries(data);}},encodeURIComponent,Blob,URL:{createObjectURL(b){blob=b;return 'blob:test';},revokeObjectURL(){}},setTimeout(){},matchMedia:()=>({matches:true})};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../../services/brief.js'),'utf8'),context);
 return {form,status,clicks,document,getBlob:()=>blob};
}
test('brief validates whitespace and opens no WhatsApp link for invalid fields',()=>{const s=setup({business:'  ',goal:'test',service:'AI integration'});s.form.onsubmit({preventDefault(){}});assert.equal(s.clicks.length,0);});
test('brief encodes special characters and newlines with no blank optional section',()=>{const s=setup({business:' Café & Co + #1 ',goal:'Build a site?\nAI & content 👋',service:'Websites & development',timeframe:''});s.form.onsubmit({preventDefault(){}});const link=s.clicks[0],url=new URL(link.href);assert.equal(url.origin,'https://api.whatsapp.com');assert.equal(url.pathname,'/send/');assert.equal(url.searchParams.get('phone'),'27833110552');assert.equal(url.searchParams.size,2);const message=url.searchParams.get('text');assert.ok(message.includes('Business: Café & Co + #1'),message);assert.ok(message.includes('Build a site?\nAI & content 👋'),message);assert.ok(!message.includes('Timeframe:'));assert.equal(link.rel,'noopener noreferrer');assert.equal(link.target,'_blank');assert.match(s.status.textContent,/press Send/);});
test('brief includes supplied timeframe and keeps download as a separate action',async()=>{const s=setup({business:'Test',goal:'Website',service:'Software development',timeframe:'September'});s.form.onsubmit({preventDefault(){}});assert.match(new URL(s.clicks[0].href).searchParams.get('text'),/Timeframe: September/);s.document.getElementById('download-brief').onclick();assert.equal(s.clicks[1].download,'zionflow-project-brief.txt');assert.match(await s.getBlob().text(),/Not submitted to ZionFlow/);});
test('public support and dashboard support are separated and use only generic messages',()=>{for(const file of ['index.html','services/index.html']){const {document}=parseHTML(fs.readFileSync(path.join(__dirname,'../..',file),'utf8'));const link=document.querySelector('.zion-support');assert.equal(new URL(link.href).searchParams.get('text'),'Hi ZionFlow I need some help.');assert.ok(link.getAttribute('aria-label'));assert.equal(link.querySelector('svg').getAttribute('aria-hidden'),'true');}const {document}=parseHTML(fs.readFileSync(path.join(__dirname,'../../growth-pro/index.html'),'utf8'));assert.equal(document.querySelector('.zion-support'),null);assert.match(new URL(document.querySelector('.support-link').href).searchParams.get('text'),/Growth Pro customer/);});
