const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');const {test}=require('node:test');const {parseHTML}=require('linkedom');
const root=path.join(__dirname,'../../');
async function setup({configured=true,sdk=true,draft=null}={}){
 const {document}=parseHTML(fs.readFileSync(root+'growth-pro/index.html','utf8'));
 for(const form of document.querySelectorAll('form')){Object.defineProperty(form,'elements',{value:[...form.querySelectorAll('input,textarea,button')]});form.reset=()=>{for(const input of form.querySelectorAll('input,textarea'))input.value='';};}
 const control={mode:'active',intervals:[],timers:[],requests:[],user:{id:'account-a'},draft};
 const auth={auth:{getSession:async()=>({data:{session:control.user?{access_token:'fixture',user:control.user}:null}}),mfa:{getAuthenticatorAssuranceLevel:async()=>({data:{currentLevel:control.aal||'aal2'}}),listFactors:async()=>({data:{totp:[],all:control.pendingFactor?[{id:'pending-factor',factor_type:'totp',status:'unverified'}]:[]}}),unenroll:async({factorId})=>{control.unenrolled=factorId;return {};},enroll:async()=>({data:{id:'new-factor',totp:{qr_code:'data:image/svg+xml,<svg/>'}}})},onAuthStateChange(callback){control.authEvent=callback;},signOut:async()=>{control.user=null;control.authEvent('SIGNED_OUT');return {};}}};
 const workspace={email:'test@example.test',profile:{businessName:'<img src=x onerror=alert(1)>'},assessment:{score:56,areas:[{name:'Visibility',score:7}],completedAt:'2026-09-09'},tasks:[{id:'task1',title:'Test action',area:'Visibility',completed:false}],membership:{paid_until:new Date(Date.now()+3600000).toISOString()}};
 const context={document,window:{...(sdk?{supabase:{createClient:()=>auth}}:{}),ZIONFLOW_CONFIG:{},addEventListener(){}},navigator:{},location:{origin:'https://example.test'},localStorage:{getItem(){return control.draft;},removeItem(){control.draft=null;}},fetch:async(url,options)=>{control.requests.push({url,options});if(url.endsWith('/config'))return Response.json({configured,authUrl:'https://example.test',authKey:'fixture'});if(control.mode==='outage')throw Error('Offline');if(control.mode==='expired')return Response.json({code:'SUBSCRIPTION_REQUIRED',error:'Membership expired'},{status:402});if(control.mode==='denied-then-outage'){control.mode='outage';return Response.json({code:'SUBSCRIPTION_REQUIRED',error:'Membership expired'},{status:402});}return Response.json(structuredClone(workspace));},AbortSignal,setInterval(fn){control.intervals.push(fn);},setTimeout(fn,ms){control.timers.push({fn,ms});return control.timers.length;},clearTimeout(){},console,Date:class Clock extends Date{static now(){return control.now||Date.now();}}};vm.createContext(context);
 await vm.runInContext('(async()=>{'+fs.readFileSync(root+'growth-pro/workspace.js','utf8')+'})()',context);
 return {document,control};
}
test('dashboard renders verified data as text and clears it on expired access',async()=>{const {document,control}=await setup();assert.equal(document.getElementById('app').hidden,false);assert.equal(document.getElementById('score').textContent,'56');assert.equal(document.getElementById('welcome').querySelector('img'),null);control.mode='expired';await document.getElementById('check-access').onclick();assert.equal(document.getElementById('app').hidden,true);assert.equal(document.getElementById('billing-gate').hidden,false);assert.equal(document.querySelectorAll('#all-tasks input').length,0);});
test('membership denial locks immediately even if a follow-up request would fail',async()=>{const {document,control}=await setup();control.mode='denied-then-outage';await control.intervals[0]();assert.equal(document.getElementById('app').hidden,true);});
test('sign-out leaves a usable sign-in form, not a hidden form',async()=>{const {document,control}=await setup();control.mode='expired';await document.getElementById('check-access').onclick();control.authEvent('SIGNED_OUT');assert.equal(document.getElementById('login-form').hidden,false);assert.equal(document.getElementById('billing-gate').hidden,true);});
test('missing auth service disables sign-in rather than pretending it works',async()=>{const {document}=await setup({configured:false});assert.equal(document.getElementById('login-submit').disabled,true);assert.match(document.getElementById('auth-message').textContent,/connected/);});
test('missing auth SDK is shown as a recoverable unavailable state',async()=>{const {document}=await setup({sdk:false});assert.equal(document.getElementById('login-submit').disabled,true);assert.equal(document.getElementById('auth-message').hidden,false);});
test('pending assessment is submitted only to authenticated account API and removed after success',async()=>{const {control}=await setup({draft:JSON.stringify({answers:Array(8).fill(1)})});const request=control.requests.find(r=>r.url.endsWith('/assessment'));assert.deepEqual(JSON.parse(request.options.body),{answers:Array(8).fill(1)});assert.equal(control.draft,null);});
test('paid-through deadline locks locally while offline',async()=>{const {document,control}=await setup();control.mode='outage';control.now=Date.now()+7200000;control.timers.at(-1).fn();assert.equal(document.getElementById('app').hidden,true);});
test('MFA enrollment handles a pending factor from the SDK all-factors list',async()=>{const {document,control}=await setup();control.aal='aal1';control.pendingFactor=true;await document.getElementById('check-access').onclick();assert.equal(control.unenrolled,'pending-factor');assert.equal(document.getElementById('mfa-form').hidden,false);assert.equal(document.getElementById('mfa-qr').hidden,false);});
