import { site } from './site.config.js';
export const escapeHTML = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e = escapeHTML;
export function contactURL(kind, config=site) {
  if (kind==='phone' && /^\+[1-9]\d{7,14}$/.test(config.phone || '')) return `tel:${config.phone}`;
  if (kind==='whatsapp' && /^[1-9]\d{7,14}$/.test(config.whatsapp || '')) return `https://wa.me/${config.whatsapp}`;
  return '#quote';
}
const paths = {
  arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',
  diagonal:'<path d="M6 18 18 6M6 6h12v12"/>',
  home:'<path d="m3 10 9-7 9 7v11h-7v-7h-4v7H3Z"/>',
  bolt:'<path d="m14 2-9 12h6l-1 8 9-12h-6Z"/>',
  drop:'<path d="M12 2S5 10 5 15a7 7 0 0 0 14 0C19 10 12 2 12 2Z"/><path d="M9 15a3 3 0 0 0 3 3"/>',
  tool:'<path d="m14 6 4 4 4-4a7 7 0 0 1-9 9l-6 6a3 3 0 0 1-4-4l6-6a7 7 0 0 1 9-9Z"/>',
  layers:'<path d="m12 3 10 6-10 6L2 9ZM2 14l10 6 10-6"/>',
  sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',
  phone:'<path d="m5 3 4-1 3 6-3 2c1 3 2 4 5 5l2-3 6 3-1 4c-1 5-8 1-12-3S0 4 5 3Z"/>',
  check:'<path d="m5 12 4 4L19 6"/>',
  pin:'<path d="M19 9c0 5-7 12-7 12S5 14 5 9a7 7 0 0 1 14 0Z"/><circle cx="12" cy="9" r="2"/>',
};
const icon=(name)=>`<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.arrow}</svg>`;
const contact=(kind,label,cls='')=>`<a class="${cls}" href="${e(contactURL(kind))}" ${contactURL(kind)==='#quote'?`data-contact="${kind}"`:''}>${label}</a>`;
export function renderSite() { return `
<a class="skip" href="#main">Skip to content</a>
<div class="demo-ribbon">ZIONFLOW CONCEPT 01 <span>Fictional business · Preview experience</span><a href="#about-demo">About this demo ${icon('diagonal')}</a></div>
<header class="header"><a class="brand" href="#" aria-label="${e(site.brand)} home"><span class="brand-mark" aria-hidden="true">F<span></span></span><span>${e(site.brand)}<small>${e(site.descriptor)}</small></span></a>
<button class="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Open navigation"><span></span><span></span></button>
<nav id="navigation" aria-label="Main navigation"><a href="#services">What we do</a><a href="#work">Our approach</a><a href="#areas">Service areas</a><a href="#quote" class="button button-small">Let’s talk ${icon('diagonal')}</a></nav></header>
<main id="main">
<section class="hero" aria-labelledby="hero-heading"><picture><source media="(max-width: 640px)" srcset="${e(site.heroImageSmall)}"><img class="hero-image" src="${e(site.heroImage)}" width="1672" height="941" fetchpriority="high" alt="${e(site.heroAlt)}"></picture><div class="hero-shade"></div>
<div class="hero-content"><p class="eyebrow"><i></i>${e(site.eyebrow)}</p><h1 id="hero-heading">${e(site.headline[0])}<br><em>${e(site.headline[1])}</em></h1><p class="hero-intro">${e(site.intro)}</p><div class="hero-actions"><a href="#quote" class="button">Start your project ${icon('diagonal')}</a><a href="#services" class="text-link">Explore our services ${icon('arrow')}</a></div></div>
<div class="hero-bottom"><span>${icon('pin')} ${e(site.city)} & surrounds</span><span>SPACES TO FEEL AT HOME IN.</span><a href="#services" aria-label="Discover services">↓</a></div><span class="image-note">AI-generated architectural concept</span></section>
<div class="promise-strip">${site.promises.map(x=>`<span>${icon('check')}${e(x)}</span>`).join('')}</div>
<section class="section services" id="services"><div class="section-heading"><div><p class="eyebrow">01 / WHAT WE DO</p><h2>${e(site.servicesIntro)}</h2></div><p>${e(site.servicesDescription)}</p></div>
<div class="services-grid">${site.services.map((s,i)=>`<a class="service" href="#quote" data-service="${e(s.id)}"><div class="service-top">${icon(s.icon)}<span>0${i+1}</span></div><h3>${e(s.name)}</h3><p>${e(s.description)}</p><div class="service-bottom"><span>${e(s.tags)}</span>${icon('diagonal')}</div></a>`).join('')}</div></section>
<section class="section work" id="work"><div class="section-heading"><div><p class="eyebrow">02 / THE BIGGER PICTURE</p><h2>${e(site.project.title)}</h2></div><p>${e(site.project.description)}</p></div>
<div class="project-visual"><img src="${e(site.heroImage)}" alt="${e(site.heroAlt)}" width="1672" height="941" loading="lazy"><div class="project-label"><span>THE RESIDENCE</span><small>${e(site.project.location)}</small></div><span class="concept-label">ILLUSTRATIVE PROJECT</span>${site.project.details.map((d,i)=>`<button class="hotspot hotspot-${i} ${i===0?'active':''}" data-detail="${i}" aria-label="Explore ${e(d.title)}" aria-pressed="${i===0}">${String(i+1).padStart(2,'0')}</button>`).join('')}</div>
<div class="project-details">${site.project.details.map((d,i)=>`<button class="detail ${i===0?'active':''}" data-detail="${i}" aria-pressed="${i===0}"><span>0${i+1}</span><h3>${e(d.title)} ${icon('diagonal')}</h3><p>${e(d.text)}</p></button>`).join('')}</div><p class="fine-print">Concept imagery and project details demonstrate the experience. They do not represent completed client work.</p></section>
<section class="process-band"><div><p class="eyebrow">A SIMPLER WAY FORWARD</p><h2>Good work starts<br>with a conversation.</h2><a class="text-link" href="#quote">Tell us what you have in mind ${icon('diagonal')}</a></div><ol><li><span>01</span><div><h3>Tell us about your space</h3><p>Share the job, your location and what you want to achieve.</p></div></li><li><span>02</span><div><h3>Find the right approach</h3><p>Discuss the scope, the practical details and the next step.</p></div></li><li><span>03</span><div><h3>Bring it all together</h3><p>Agree on a clear plan before any work begins.</p></div></li></ol></section>
<section class="section reviews"><div class="section-heading"><div><p class="eyebrow">03 / THE EXPERIENCE</p><h2>It’s how you feel<br>about the whole job.</h2></div><p>Real customer voices belong here.<br><strong>These are sample testimonials for this demo.</strong></p></div><div class="review-grid">${site.reviews.map(r=>`<figure class="review"><span class="quote-mark" aria-hidden="true">“</span><blockquote>${e(r.quote)}</blockquote><figcaption><span class="review-avatar" aria-hidden="true">${icon('home')}</span><span>${e(r.author)}<small>${e(r.context)}</small></span><span class="sample-label">SAMPLE</span></figcaption></figure>`).join('')}</div></section>
<section class="section areas" id="areas"><div><p class="eyebrow">04 / IN YOUR NEIGHBOURHOOD</p><h2>${e(site.coverageHeading)}</h2><p>${e(site.coverageDescription)}</p><form id="area-form"><label for="suburb">Find your area</label><div class="area-input"><select id="suburb" name="suburb" required><option value="">Select a suburb</option>${site.areas.map(a=>`<option>${e(a)}</option>`).join('')}<option value="other">Somewhere else</option></select><button class="button" type="submit" aria-label="Check service area">${icon('arrow')}</button></div></form><p id="area-result" class="area-result" aria-live="polite">Example coverage · ${e(site.city)}</p></div><div class="area-panel"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="area-centre">${icon('pin')}<span>${e(site.city)}<small>OUR EXAMPLE SERVICE AREA</small></span></div><div class="area-tags">${site.areas.map(a=>`<button type="button" data-area="${e(a)}">${e(a)} ${icon('diagonal')}</button>`).join('')}</div></div></section>
<section class="quote-section" id="quote"><div class="quote-heading"><p class="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>${e(site.quoteHeading)}</h2><p>${e(site.quoteIntro)}</p><div class="quote-contact">${contact('phone',`${icon('phone')} Call us`,'text-link')}${contact('whatsapp',`WhatsApp ${icon('diagonal')}`,'text-link')}</div><p class="fine-print">${site.demo?'Demo mode: no calls or messages are sent. Your details stay in this browser tab.':'Your enquiry is prepared on your device. You choose whether to send it.'}</p></div>
<form class="quote-form" id="quote-form"><div class="form-top"><span>LET’S GET THE DETAILS</span><span>↗</span></div><div class="form-row"><div><label for="name">Your name</label><input id="name" name="name" autocomplete="name" maxlength="100" placeholder="How should we address you?" required></div><div><label for="contact">Email or phone</label><input id="contact" name="contact" autocomplete="email" maxlength="160" placeholder="Where can we reach you?" required></div></div><div class="form-row"><div><label for="service">What can we help with?</label><select id="service" name="service" required><option value="">Choose a service</option>${site.services.map(s=>`<option value="${e(s.id)}">${e(s.name)}</option>`).join('')}<option value="other">Something else</option></select></div><div><label for="location">Your suburb</label><input id="location" name="location" autocomplete="address-level2" maxlength="100" placeholder="e.g. ${e(site.areas[0])}" required></div></div><label for="message">A little about your project</label><textarea id="message" name="message" rows="3" maxlength="2000" placeholder="Tell us about your space and what you have in mind." required></textarea><button type="submit" class="button">${site.demo?'Preview my enquiry':'Prepare my enquiry'} ${icon('diagonal')}</button><p class="form-note">${site.demo?'Try the complete quote experience. Nothing is submitted.':'Review your enquiry before you send it.'}</p></form></section>
</main><footer><div class="footer-main"><a class="brand" href="#"><span class="brand-mark" aria-hidden="true">F<span></span></span><span>${e(site.brand)}<small>${e(site.descriptor)}</small></span></a><p>Considered work.<br>Spaces that feel like you.</p><a href="#main" class="text-link">Back to top ↑</a></div><div class="footer-bottom" id="about-demo"><span>© ${new Date().getFullYear()} ${e(site.brand)} · Fictional demonstration brand</span><span>A website concept by <strong>ZIONFLOW</strong></span><button type="button" id="demo-info">Demo & privacy</button></div></footer>
<div class="mobile-cta">${contact('phone',`${icon('phone')} Call`)}${contact('whatsapp','WhatsApp')}<a href="#quote">Get a quote ${icon('diagonal')}</a></div>
<dialog id="result-dialog" aria-labelledby="dialog-title"><button class="dialog-close" aria-label="Close dialog">×</button><p class="eyebrow">${e(site.brand)} / YOUR ENQUIRY</p><h2 id="dialog-title">Your enquiry, ready to review.</h2><p id="dialog-message"></p><pre id="enquiry-summary"></pre><div class="dialog-actions"><button id="download-enquiry" class="button">Save enquiry ${icon('diagonal')}</button><a id="send-whatsapp" class="button" hidden>Continue to WhatsApp</a><button class="dialog-close-text text-link">Back to the website</button></div></dialog>
<noscript><p class="noscript">Enable JavaScript to try the interactive quote and coverage features. This is a demonstration website.</p></noscript>`; }
