import assert from 'node:assert/strict';
import {readFileSync, existsSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import {renderSite, contactURL, escapeHTML} from '../src/render.js';
import {site, industryPresets} from '../src/site.config.js';
const html=renderSite();
const dom=new JSDOM(`<!doctype html><html><body>${html}</body></html>`,{url:'http://localhost/',runScripts:'outside-only'});
const {window:w}=dom;const d=w.document;
w.matchMedia=()=>({matches:false});
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;};
let objectURLCreated=false;
w.URL.createObjectURL=()=>{objectURLCreated=true;return 'blob:test';};w.URL.revokeObjectURL=()=>{};
w.HTMLAnchorElement.prototype.click=function(){if(this.download)return;this.dispatchEvent(new w.MouseEvent('click',{bubbles:true,cancelable:true}));};
w.site=site;w.contactURL=contactURL;
w.eval(readFileSync(new URL('../src/main.js',import.meta.url),'utf8').replace(/^import .*;$/gm,''));
const $=s=>d.querySelector(s);const click=s=>$(s).click();
// Real interaction handlers against a DOM, without launching or claiming browser rendering QA.
assert.equal(d.querySelectorAll('h1').length,1);
for(const a of d.querySelectorAll('a[href^="#"]')){const id=a.getAttribute('href').slice(1);if(id)assert.ok(d.getElementById(id),`Broken anchor: ${id}`);}
for(const input of d.querySelectorAll('input,select,textarea'))assert.ok(d.querySelector(`label[for="${input.id}"]`));
assert.equal(contactURL('phone'),'#quote');assert.equal(contactURL('whatsapp'),'#quote');
assert.equal(contactURL('phone',{phone:'+27123456789'}),'tel:+27123456789');
assert.equal(contactURL('phone',{phone:'javascript:alert(1)'}),'#quote');
assert.equal(contactURL('whatsapp',{whatsapp:'27123456789'}),'https://wa.me/27123456789');
assert.equal(contactURL('whatsapp',{whatsapp:'bad?text=oops'}),'#quote');
assert.equal(escapeHTML('<script>"&'), '&lt;script&gt;&quot;&amp;');
click('.menu-toggle');assert.equal($('.menu-toggle').getAttribute('aria-expanded'),'true');
d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal($('.menu-toggle').getAttribute('aria-expanded'),'false');assert.equal(d.activeElement,$('.menu-toggle'));
click('.menu-toggle');click('#navigation a');assert.equal($('.menu-toggle').getAttribute('aria-expanded'),'false');
click('[data-service="plumbing"]');assert.equal($('#service').value,'plumbing');
click('[data-area="Sandton"]');assert.equal($('#location').value,'Sandton');assert.match($('#area-result').textContent,/Sandton/);
$('#suburb').value='other';$('#area-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal($('#location').value,'');assert.match($('#area-result').textContent,/Outside/);
click('[data-detail="2"]');assert.equal(d.querySelectorAll('[data-detail="2"][aria-pressed="true"]').length,2);assert.equal(d.querySelectorAll('[data-detail="0"][aria-pressed="true"]').length,0);
click('[data-contact]');assert.equal($('#result-dialog').open,true);assert.match($('#dialog-message').textContent,/fictional/);click('.dialog-close');
const form=$('#quote-form');const submit=()=>form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
submit();assert.equal($('#result-dialog').open,false);assert.equal(form.checkValidity(),false);
const fill=(id,value)=>{$('#'+id).value=value;$('#'+id).dispatchEvent(new w.Event('input',{bubbles:true}));};
fill('name',' ');fill('contact','invalid');fill('location','Sandton');fill('message','A repair');submit();assert.equal($('#result-dialog').open,false);
fill('name','Demo Visitor');fill('contact','test@example.com');fill('message','<script>alert(1)</script>');submit();assert.equal($('#result-dialog').open,true);assert.match($('#dialog-message').textContent,/Nothing has been sent/);assert.match($('#enquiry-summary').textContent,/<script>/);assert.equal($('#enquiry-summary script'),null);assert.equal($('#send-whatsapp').hidden,true);
click('#download-enquiry');assert.equal(objectURLCreated,true);
for(const path of [site.heroImage,site.heroImageSmall])assert.ok(existsSync(new URL('../public'+path,import.meta.url)));
assert.equal(Object.keys(industryPresets).length,6);
const css=readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');assert.match(css,/@media\(max-width:720px\)/);assert.match(css,/prefers-reduced-motion:reduce/);
const built=readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');assert.ok(built.includes('noindex, nofollow'));assert.ok(built.includes('A better home.'));assert.ok(!built.includes('<!--SITE-->'));
console.log('PASS: static HTML/anchors/labels, safe contacts, menu/Escape, service selection, coverage changes, project selection, required/invalid fields, escaped quote preview, local download, responsive/reduced-motion rules, personalization presets and built SEO.');
console.log('DOM interactions were tested in jsdom; no browser layout, Lighthouse or deployed-header measurements are claimed.');
w.close();
